name: Shadowsocks Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Shadowsocks
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install https://github.com/shadowsocks/shadowsocks/archive/master.zip

      - name: Run Shadowsocks server
        run: |
          nohup sslocal -s 0.0.0.0 -p 8388 -k mypassword123 -m aes-256-cfb &
